# Generated by Django 3.2.3 on 2021-06-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.TextField(max_length=50, null=True)),
                ('complement', models.TextField(max_length=50, null=True)),
                ('code_postale', models.TextField(max_length=50, null=True)),
                ('ville_salarie', models.TextField(max_length=50, null=True)),
                ('address_salarie', models.TextField(max_length=50, null=True)),
                ('hors_france_salarie', models.BooleanField(default=False)),
                ('pays_code_salarie', models.TextField(max_length=4, null=True)),
                ('pays_nom_salarie', models.TextField(max_length=50, null=True)),
                ('tel_domicile', models.TextField(max_length=20, null=True)),
                ('tel_bureau', models.TextField(max_length=20, null=True)),
                ('tel_portable', models.TextField(max_length=20, null=True)),
                ('tel_portable_pros', models.TextField(max_length=20, null=True)),
                ('email_salarie', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_emploi', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(max_length=20)),
                ('duree_mois', models.SmallIntegerField(null=True)),
                ('duree_jours', models.SmallIntegerField(null=True)),
                ('date_debut_emploi', models.DateField()),
                ('motif_debut_emploi', models.TextField(max_length=250, null=True)),
                ('date_fin_emploi', models.DateField(null=True)),
                ('motif_fin_emploi', models.TextField(max_length=250, null=True)),
                ('code_metier', models.TextField(max_length=10, null=True)),
                ('salaire_brute', models.FloatField()),
                ('type_salaire', models.CharField(blank=True, choices=[('Horaire', 'Horaire')], max_length=10)),
                ('heure_normale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EtapeCreationSalarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.BooleanField(default=False)),
                ('coordonnees', models.BooleanField(default=False)),
                ('bancaire', models.BooleanField(default=False)),
                ('emploi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salarie', models.CharField(max_length=50)),
                ('prenom_salarie', models.CharField(max_length=50)),
                ('sexe', models.CharField(blank=True, choices=[('Feminin', 'Feminin')], max_length=10)),
                ('nom_maritale', models.CharField(max_length=50, null=True)),
                ('matricule', models.CharField(max_length=50, null=True)),
                ('matricule_interne', models.CharField(max_length=50, null=True)),
                ('nir', models.CharField(max_length=15)),
                ('situation_familiale', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire')], max_length=15)),
                ('date_naissance', models.DateField()),
                ('pay_naissance', models.TextField(max_length=50, null=True)),
                ('commune_naissance', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.TextField(max_length=50)),
                ('locale', models.TextField(max_length=50)),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('activiter', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordonnees', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.coordonnees')),
                ('emploi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.emploi')),
                ('etape_creation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.etapecreationsalarie')),
                ('identification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.identification')),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='InformationBancaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.TextField(max_length=20)),
                ('iban', models.TextField(max_length=20)),
                ('bic', models.TextField(max_length=20)),
                ('virement', models.BooleanField(default=False)),
                ('plafond', models.FloatField(null=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.salarie')),
            ],
        ),
    ]
