# Generated by Django 3.2.3 on 2021-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_model', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_motif', models.CharField(max_length=100)),
                ('isPrime', models.BooleanField(default=False)),
                ('isAbsence', models.BooleanField(default=False)),
                ('isHeure', models.BooleanField(default=False)),
                ('isIndemniter', models.BooleanField(default=False)),
                ('isAutre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHaut', models.BooleanField(default=False)),
                ('isBas', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.bulletinmodel')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.motifs')),
            ],
        ),
        migrations.AddField(
            model_name='bulletinmodel',
            name='motifs',
            field=models.ManyToManyField(through='subscriptions.ModelMotif', to='subscriptions.Motifs'),
        ),
        migrations.AddField(
            model_name='bulletinmodel',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.societe'),
        ),
    ]
