# Generated by Django 3.2.3 on 2021-07-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_motif', models.CharField(max_length=100)),
                ('isPrime', models.BooleanField(default=False)),
                ('isAbsence', models.BooleanField(default=False)),
                ('isHeure', models.BooleanField(default=False)),
                ('isIndemniter', models.BooleanField(default=False)),
                ('isAutre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_model', models.CharField(max_length=100, null=True)),
                ('motifs', models.ManyToManyField(to='subscriptions.Motifs')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.societe')),
            ],
        ),
    ]
