# Generated by Django 3.2.3 on 2021-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_coordonnees_emploi_etapecreationsalarie_identification_informationbancaire_salarie_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('Célibataire', 'Célibataire')], max_length=15),
        ),
    ]
