# Generated by Django 3.2.3 on 2021-05-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_salarie_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarie',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.societe'),
        ),
    ]
