# Generated by Django 3.2.3 on 2021-05-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_salarie_societe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarie',
            old_name='empoi',
            new_name='emploi',
        ),
    ]
