# Generated by Django 3.2.3 on 2021-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_rename_empoi_salarie_emploi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='CDD',
        ),
        migrations.AddField(
            model_name='emploi',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDD', 'Cdd')], max_length=3),
        ),
    ]
