# Generated by Django 3.2.3 on 2021-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210520_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='type_salaire',
            field=models.CharField(blank=True, choices=[('Horaire', 'Horaire')], max_length=10),
        ),
    ]
