# Generated by Django 3.2.3 on 2021-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_emploi_type_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Féminin', 'Féminin')], max_length=10),
        ),
    ]
