# Generated by Django 3.2.3 on 2021-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_identification_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Feminin', 'Feminin')], max_length=10),
        ),
    ]
